export const START_GET_DRINKS = 'START_GET_DRINKS';
export const DRINKS_IS_LOADING = 'DRINKS_IS_LOADING';
export const DRINKS_FETCH_SUCCESS = 'DRINKS_FETCH_SUCCESS'
export const DRINKS_HAS_ERRORED = 'DRINKS_HAS_ERRORED'